re:ET INFO.*Dotted Quad
re:ET INFO.*(?:Pastebin-like|Pastebin-style)
re:ET INFO.*(?:URL Shortener|URL Shortening)
re:ET INFO.*External IP
re:ET INFO.*DNS Over HTTPS
re:RMM
re:Network Tunneling Service
#t.me in TLS SNI
2041933
2033966
2033967
re:ET INFO.*Discord
re: workers .dev
re: pages .dev
